CREATE TABLE USERS (
    US_ID INT AUTO_INCREMENT,
    US_FIRST_NAME VARCHAR(100) NOT NULL,
    US_SECOND_NAME VARCHAR(100),
    US_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    US_ROLE ENUM ('CLIENT', 'EMPLOYEE', 'ADMIN') NOT NULL DEFAULT 'CLIENT',
    PRIMARY KEY (US_ID)
);